[2018-08-20 17:02:30,015] INFO [GroupCoordinator 0]: Preparing to rebalance group 433bd343-a7f8-479c-9425-18168b45a2ce with old generation 0 (__consumer_offsets-23) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:02:30,018] INFO [GroupCoordinator 0]: Stabilized group 433bd343-a7f8-479c-9425-18168b45a2ce generation 1 (__consumer_offsets-23) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:02:30,019] INFO [GroupCoordinator 0]: Assignment received from leader for group 433bd343-a7f8-479c-9425-18168b45a2ce for generation 1 (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:02:30,020] INFO Updated PartitionLeaderEpoch. New: {epoch:0, offset:0}, Current: {epoch:-1, offset:-1} for Partition: __consumer_offsets-23. Cache now contains 0 entries. (kafka.server.epoch.LeaderEpochFileCache)
[2018-08-20 17:02:34,585] INFO [GroupCoordinator 0]: Member sarama-c9bc6e3a-fec3-4270-bd30-ec97f2d9a68d in group c8039b18-d57d-4974-bc0e-8930834cc7e2 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:02:34,585] INFO [GroupCoordinator 0]: Preparing to rebalance group c8039b18-d57d-4974-bc0e-8930834cc7e2 with old generation 1 (__consumer_offsets-9) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:02:34,586] INFO [GroupCoordinator 0]: Group c8039b18-d57d-4974-bc0e-8930834cc7e2 with generation 2 is now empty (__consumer_offsets-9) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:04:23,891] INFO [GroupMetadataManager brokerId=0] Group c8039b18-d57d-4974-bc0e-8930834cc7e2 transitioned to Dead in generation 2 (kafka.coordinator.group.GroupMetadataManager)
[2018-08-20 17:04:23,892] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 1 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2018-08-20 17:05:34,594] INFO [GroupCoordinator 0]: Preparing to rebalance group 90afedca-8d77-4904-ac2f-7aabe8ada347 with old generation 0 (__consumer_offsets-44) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:05:34,595] INFO [GroupCoordinator 0]: Stabilized group 90afedca-8d77-4904-ac2f-7aabe8ada347 generation 1 (__consumer_offsets-44) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:05:34,595] INFO [GroupCoordinator 0]: Preparing to rebalance group d8332ad4-ddc2-4196-88e3-f411f77dde51 with old generation 0 (__consumer_offsets-3) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:05:34,596] INFO [GroupCoordinator 0]: Stabilized group d8332ad4-ddc2-4196-88e3-f411f77dde51 generation 1 (__consumer_offsets-3) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:05:34,596] INFO [GroupCoordinator 0]: Assignment received from leader for group 90afedca-8d77-4904-ac2f-7aabe8ada347 for generation 1 (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:05:34,597] INFO Updated PartitionLeaderEpoch. New: {epoch:0, offset:0}, Current: {epoch:-1, offset:-1} for Partition: __consumer_offsets-44. Cache now contains 0 entries. (kafka.server.epoch.LeaderEpochFileCache)
[2018-08-20 17:05:34,597] INFO [GroupCoordinator 0]: Assignment received from leader for group d8332ad4-ddc2-4196-88e3-f411f77dde51 for generation 1 (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:05:34,597] INFO Updated PartitionLeaderEpoch. New: {epoch:0, offset:0}, Current: {epoch:-1, offset:-1} for Partition: __consumer_offsets-3. Cache now contains 0 entries. (kafka.server.epoch.LeaderEpochFileCache)
[2018-08-20 17:05:48,252] INFO [GroupCoordinator 0]: Preparing to rebalance group b5bbb27b-a5b5-4ab6-b3fd-f23ea73371cf with old generation 0 (__consumer_offsets-42) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:05:48,255] INFO [GroupCoordinator 0]: Stabilized group b5bbb27b-a5b5-4ab6-b3fd-f23ea73371cf generation 1 (__consumer_offsets-42) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:05:48,256] INFO [GroupCoordinator 0]: Preparing to rebalance group 00e89566-527e-4fa7-92e1-616ea15c7384 with old generation 0 (__consumer_offsets-7) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:05:48,256] INFO [GroupCoordinator 0]: Assignment received from leader for group b5bbb27b-a5b5-4ab6-b3fd-f23ea73371cf for generation 1 (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:05:48,258] INFO [GroupCoordinator 0]: Stabilized group 00e89566-527e-4fa7-92e1-616ea15c7384 generation 1 (__consumer_offsets-7) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:05:48,259] INFO [GroupCoordinator 0]: Assignment received from leader for group 00e89566-527e-4fa7-92e1-616ea15c7384 for generation 1 (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:05:48,259] INFO Updated PartitionLeaderEpoch. New: {epoch:0, offset:0}, Current: {epoch:-1, offset:-1} for Partition: __consumer_offsets-7. Cache now contains 0 entries. (kafka.server.epoch.LeaderEpochFileCache)
[2018-08-20 17:08:19,878] INFO [GroupCoordinator 0]: Preparing to rebalance group fbfbbc38-e9e2-4ba3-a68a-9bc5f8683edb with old generation 0 (__consumer_offsets-26) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:08:19,879] INFO [GroupCoordinator 0]: Stabilized group fbfbbc38-e9e2-4ba3-a68a-9bc5f8683edb generation 1 (__consumer_offsets-26) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:08:19,879] INFO [GroupCoordinator 0]: Preparing to rebalance group f9239008-3ba6-4486-8ee6-3e168f94cd63 with old generation 0 (__consumer_offsets-27) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:08:19,880] INFO [GroupCoordinator 0]: Assignment received from leader for group fbfbbc38-e9e2-4ba3-a68a-9bc5f8683edb for generation 1 (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:08:19,880] INFO [GroupCoordinator 0]: Stabilized group f9239008-3ba6-4486-8ee6-3e168f94cd63 generation 1 (__consumer_offsets-27) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:08:19,881] INFO [GroupCoordinator 0]: Assignment received from leader for group f9239008-3ba6-4486-8ee6-3e168f94cd63 for generation 1 (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:08:19,881] INFO Updated PartitionLeaderEpoch. New: {epoch:0, offset:0}, Current: {epoch:-1, offset:-1} for Partition: __consumer_offsets-27. Cache now contains 0 entries. (kafka.server.epoch.LeaderEpochFileCache)
[2018-08-20 17:10:38,690] INFO [GroupCoordinator 0]: Preparing to rebalance group 1df9c7cb-e27d-4e6e-8ed3-f8274a5bb5cf with old generation 0 (__consumer_offsets-40) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:10:38,692] INFO [GroupCoordinator 0]: Stabilized group 1df9c7cb-e27d-4e6e-8ed3-f8274a5bb5cf generation 1 (__consumer_offsets-40) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:10:38,693] INFO [GroupCoordinator 0]: Preparing to rebalance group 19e2fb51-aede-406f-9076-03018b57b4d2 with old generation 0 (__consumer_offsets-32) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:10:38,694] INFO [GroupCoordinator 0]: Assignment received from leader for group 1df9c7cb-e27d-4e6e-8ed3-f8274a5bb5cf for generation 1 (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:10:38,694] INFO [GroupCoordinator 0]: Stabilized group 19e2fb51-aede-406f-9076-03018b57b4d2 generation 1 (__consumer_offsets-32) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:10:38,695] INFO [GroupCoordinator 0]: Assignment received from leader for group 19e2fb51-aede-406f-9076-03018b57b4d2 for generation 1 (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:10:38,696] INFO Updated PartitionLeaderEpoch. New: {epoch:0, offset:0}, Current: {epoch:-1, offset:-1} for Partition: __consumer_offsets-32. Cache now contains 0 entries. (kafka.server.epoch.LeaderEpochFileCache)
[2018-08-20 17:10:55,878] INFO [GroupCoordinator 0]: Member sarama-83e56803-d96f-4d86-a7af-b8e2f85e8b8b in group 90afedca-8d77-4904-ac2f-7aabe8ada347 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:10:55,879] INFO [GroupCoordinator 0]: Preparing to rebalance group 90afedca-8d77-4904-ac2f-7aabe8ada347 with old generation 1 (__consumer_offsets-44) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:10:55,879] INFO [GroupCoordinator 0]: Group 90afedca-8d77-4904-ac2f-7aabe8ada347 with generation 2 is now empty (__consumer_offsets-44) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:10:56,118] INFO [GroupCoordinator 0]: Member sarama-387fb40e-acc0-41d1-adb7-fd27bb352934 in group fbfbbc38-e9e2-4ba3-a68a-9bc5f8683edb has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:10:56,118] INFO [GroupCoordinator 0]: Preparing to rebalance group fbfbbc38-e9e2-4ba3-a68a-9bc5f8683edb with old generation 1 (__consumer_offsets-26) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:10:56,118] INFO [GroupCoordinator 0]: Group fbfbbc38-e9e2-4ba3-a68a-9bc5f8683edb with generation 2 is now empty (__consumer_offsets-26) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:10:56,127] INFO [GroupCoordinator 0]: Member sarama-15c4ef55-35fb-4df7-888d-5ad22163bb77 in group d8332ad4-ddc2-4196-88e3-f411f77dde51 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:10:56,127] INFO [GroupCoordinator 0]: Preparing to rebalance group d8332ad4-ddc2-4196-88e3-f411f77dde51 with old generation 1 (__consumer_offsets-3) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:10:56,127] INFO [GroupCoordinator 0]: Group d8332ad4-ddc2-4196-88e3-f411f77dde51 with generation 2 is now empty (__consumer_offsets-3) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:10:56,130] INFO [GroupCoordinator 0]: Member sarama-6a5a4d6e-9958-4dcf-aa67-2e8339a2e70c in group f9239008-3ba6-4486-8ee6-3e168f94cd63 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:10:56,130] INFO [GroupCoordinator 0]: Preparing to rebalance group f9239008-3ba6-4486-8ee6-3e168f94cd63 with old generation 1 (__consumer_offsets-27) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:10:56,130] INFO [GroupCoordinator 0]: Group f9239008-3ba6-4486-8ee6-3e168f94cd63 with generation 2 is now empty (__consumer_offsets-27) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:10:57,137] INFO [GroupCoordinator 0]: Member sarama-a4d566d4-cc6d-4286-ba24-574eb97cc8b3 in group 433bd343-a7f8-479c-9425-18168b45a2ce has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:10:57,137] INFO [GroupCoordinator 0]: Preparing to rebalance group 433bd343-a7f8-479c-9425-18168b45a2ce with old generation 1 (__consumer_offsets-23) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:10:57,137] INFO [GroupCoordinator 0]: Group 433bd343-a7f8-479c-9425-18168b45a2ce with generation 2 is now empty (__consumer_offsets-23) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:10:57,290] INFO [GroupCoordinator 0]: Member sarama-4606a1ec-d4cd-41cf-a6a3-ebf166d10171 in group b5bbb27b-a5b5-4ab6-b3fd-f23ea73371cf has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:10:57,290] INFO [GroupCoordinator 0]: Preparing to rebalance group b5bbb27b-a5b5-4ab6-b3fd-f23ea73371cf with old generation 1 (__consumer_offsets-42) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:10:57,290] INFO [GroupCoordinator 0]: Group b5bbb27b-a5b5-4ab6-b3fd-f23ea73371cf with generation 2 is now empty (__consumer_offsets-42) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:10:57,381] INFO [GroupCoordinator 0]: Member sarama-e5ed1ccf-677b-4815-9075-e83b744f6dc0 in group 00e89566-527e-4fa7-92e1-616ea15c7384 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:10:57,381] INFO [GroupCoordinator 0]: Preparing to rebalance group 00e89566-527e-4fa7-92e1-616ea15c7384 with old generation 1 (__consumer_offsets-7) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:10:57,381] INFO [GroupCoordinator 0]: Group 00e89566-527e-4fa7-92e1-616ea15c7384 with generation 2 is now empty (__consumer_offsets-7) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:14:23,891] INFO [GroupMetadataManager brokerId=0] Group fbfbbc38-e9e2-4ba3-a68a-9bc5f8683edb transitioned to Dead in generation 2 (kafka.coordinator.group.GroupMetadataManager)
[2018-08-20 17:14:23,892] INFO [GroupMetadataManager brokerId=0] Group 00e89566-527e-4fa7-92e1-616ea15c7384 transitioned to Dead in generation 2 (kafka.coordinator.group.GroupMetadataManager)
[2018-08-20 17:14:23,893] INFO [GroupMetadataManager brokerId=0] Group b5bbb27b-a5b5-4ab6-b3fd-f23ea73371cf transitioned to Dead in generation 2 (kafka.coordinator.group.GroupMetadataManager)
[2018-08-20 17:14:23,895] INFO [GroupMetadataManager brokerId=0] Group d8332ad4-ddc2-4196-88e3-f411f77dde51 transitioned to Dead in generation 2 (kafka.coordinator.group.GroupMetadataManager)
[2018-08-20 17:14:23,895] INFO [GroupMetadataManager brokerId=0] Group 90afedca-8d77-4904-ac2f-7aabe8ada347 transitioned to Dead in generation 2 (kafka.coordinator.group.GroupMetadataManager)
[2018-08-20 17:14:23,896] INFO [GroupMetadataManager brokerId=0] Group f9239008-3ba6-4486-8ee6-3e168f94cd63 transitioned to Dead in generation 2 (kafka.coordinator.group.GroupMetadataManager)
[2018-08-20 17:14:23,896] INFO [GroupMetadataManager brokerId=0] Group 433bd343-a7f8-479c-9425-18168b45a2ce transitioned to Dead in generation 2 (kafka.coordinator.group.GroupMetadataManager)
[2018-08-20 17:14:23,897] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 6 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2018-08-20 17:15:53,897] INFO [GroupCoordinator 0]: Preparing to rebalance group 4133a219-169b-419b-9bde-86364156ae93 with old generation 0 (__consumer_offsets-37) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:15:53,898] INFO [GroupCoordinator 0]: Preparing to rebalance group 1b636ffc-75d2-482a-b47d-50c01516c15d with old generation 0 (__consumer_offsets-7) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:15:53,899] INFO [GroupCoordinator 0]: Stabilized group 4133a219-169b-419b-9bde-86364156ae93 generation 1 (__consumer_offsets-37) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:15:53,900] INFO [GroupCoordinator 0]: Stabilized group 1b636ffc-75d2-482a-b47d-50c01516c15d generation 1 (__consumer_offsets-7) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:15:53,900] INFO [GroupCoordinator 0]: Assignment received from leader for group 4133a219-169b-419b-9bde-86364156ae93 for generation 1 (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:15:53,901] INFO [GroupCoordinator 0]: Assignment received from leader for group 1b636ffc-75d2-482a-b47d-50c01516c15d for generation 1 (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:15:53,901] INFO Updated PartitionLeaderEpoch. New: {epoch:0, offset:0}, Current: {epoch:-1, offset:-1} for Partition: __consumer_offsets-37. Cache now contains 0 entries. (kafka.server.epoch.LeaderEpochFileCache)
[2018-08-20 17:16:05,813] INFO [GroupCoordinator 0]: Member sarama-8474cc34-897b-4bf6-a88b-0b3b8646b4a5 in group 19e2fb51-aede-406f-9076-03018b57b4d2 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:16:05,813] INFO [GroupCoordinator 0]: Preparing to rebalance group 19e2fb51-aede-406f-9076-03018b57b4d2 with old generation 1 (__consumer_offsets-32) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:16:05,814] INFO [GroupCoordinator 0]: Group 19e2fb51-aede-406f-9076-03018b57b4d2 with generation 2 is now empty (__consumer_offsets-32) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:16:05,815] INFO [GroupCoordinator 0]: Member sarama-8ef80f68-48b4-4f28-8f82-3670e3166b6e in group 1df9c7cb-e27d-4e6e-8ed3-f8274a5bb5cf has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:16:05,815] INFO [GroupCoordinator 0]: Preparing to rebalance group 1df9c7cb-e27d-4e6e-8ed3-f8274a5bb5cf with old generation 1 (__consumer_offsets-40) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:16:05,815] INFO [GroupCoordinator 0]: Group 1df9c7cb-e27d-4e6e-8ed3-f8274a5bb5cf with generation 2 is now empty (__consumer_offsets-40) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:19:44,244] INFO [GroupCoordinator 0]: Preparing to rebalance group 7bdcd758-6618-42f5-94e7-7410a38fc427 with old generation 0 (__consumer_offsets-33) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:19:44,246] INFO [GroupCoordinator 0]: Stabilized group 7bdcd758-6618-42f5-94e7-7410a38fc427 generation 1 (__consumer_offsets-33) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:19:44,247] INFO [GroupCoordinator 0]: Preparing to rebalance group 4a2c18c4-dd99-4dd5-a49e-89373e46ea34 with old generation 0 (__consumer_offsets-22) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:19:44,249] INFO [GroupCoordinator 0]: Stabilized group 4a2c18c4-dd99-4dd5-a49e-89373e46ea34 generation 1 (__consumer_offsets-22) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:19:44,249] INFO [GroupCoordinator 0]: Assignment received from leader for group 7bdcd758-6618-42f5-94e7-7410a38fc427 for generation 1 (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:19:44,249] INFO [GroupCoordinator 0]: Assignment received from leader for group 4a2c18c4-dd99-4dd5-a49e-89373e46ea34 for generation 1 (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:19:44,250] INFO Updated PartitionLeaderEpoch. New: {epoch:0, offset:0}, Current: {epoch:-1, offset:-1} for Partition: __consumer_offsets-33. Cache now contains 0 entries. (kafka.server.epoch.LeaderEpochFileCache)
[2018-08-20 17:19:54,036] INFO [GroupCoordinator 0]: Member sarama-faad10cf-d6f9-4255-833a-fb65a537210f in group 4133a219-169b-419b-9bde-86364156ae93 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:19:54,036] INFO [GroupCoordinator 0]: Preparing to rebalance group 4133a219-169b-419b-9bde-86364156ae93 with old generation 1 (__consumer_offsets-37) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:19:54,036] INFO [GroupCoordinator 0]: Group 4133a219-169b-419b-9bde-86364156ae93 with generation 2 is now empty (__consumer_offsets-37) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:19:54,038] INFO [GroupCoordinator 0]: Member sarama-e545defe-d8eb-443a-a952-03dc4eda4f29 in group 1b636ffc-75d2-482a-b47d-50c01516c15d has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:19:54,038] INFO [GroupCoordinator 0]: Preparing to rebalance group 1b636ffc-75d2-482a-b47d-50c01516c15d with old generation 1 (__consumer_offsets-7) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:19:54,038] INFO [GroupCoordinator 0]: Group 1b636ffc-75d2-482a-b47d-50c01516c15d with generation 2 is now empty (__consumer_offsets-7) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:22:22,610] INFO Terminating process due to signal SIGTERM (kafka.Kafka$)
[2018-08-20 17:22:22,668] INFO [GroupCoordinator 0]: Preparing to rebalance group console-consumer-14987 with old generation 1 (__consumer_offsets-30) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:22:22,668] INFO [GroupCoordinator 0]: Group console-consumer-14987 with generation 2 is now empty (__consumer_offsets-30) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:22:22,822] INFO [KafkaServer id=0] shutting down (kafka.server.KafkaServer)
[2018-08-20 17:22:22,826] INFO [KafkaServer id=0] Starting controlled shutdown (kafka.server.KafkaServer)
[2018-08-20 17:22:22,784] INFO Terminating process due to signal SIGHUP (kafka.Kafka$)
[2018-08-20 17:22:22,790] INFO Terminating process due to signal SIGHUP (kafka.Kafka$)
[2018-08-20 17:22:23,063] WARN Session 0x1655553af610011 for server localhost/127.0.0.1:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:68)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:366)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:22:23,166] INFO [ZooKeeperClient] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2018-08-20 17:22:23,166] INFO [ZooKeeperClient] Connected. (kafka.zookeeper.ZooKeeperClient)
[2018-08-20 17:22:24,448] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:22:24,449] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:22:24,570] INFO [ZooKeeperClient] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2018-08-20 17:22:26,483] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:22:26,484] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:22:27,991] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:22:27,992] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:22:29,564] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:22:29,565] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:22:30,703] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:22:30,703] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:22:32,267] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:22:32,268] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:22:33,431] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:22:33,432] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:22:35,319] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:22:35,320] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:22:36,773] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:22:36,775] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:22:38,533] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:22:38,534] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:22:39,888] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:22:39,889] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:22:41,365] INFO [GroupCoordinator 0]: Member sarama-8fa201ef-d947-4d4b-a419-309deb6e21c6 in group 4a2c18c4-dd99-4dd5-a49e-89373e46ea34 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:22:41,366] INFO [GroupCoordinator 0]: Preparing to rebalance group 4a2c18c4-dd99-4dd5-a49e-89373e46ea34 with old generation 1 (__consumer_offsets-22) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:22:41,366] INFO [GroupCoordinator 0]: Group 4a2c18c4-dd99-4dd5-a49e-89373e46ea34 with generation 2 is now empty (__consumer_offsets-22) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:22:41,367] INFO [GroupCoordinator 0]: Member sarama-5e704dd7-aed2-475d-8696-a5797f619a89 in group 7bdcd758-6618-42f5-94e7-7410a38fc427 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:22:41,367] INFO [GroupCoordinator 0]: Preparing to rebalance group 7bdcd758-6618-42f5-94e7-7410a38fc427 with old generation 1 (__consumer_offsets-33) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:22:41,367] INFO [GroupCoordinator 0]: Group 7bdcd758-6618-42f5-94e7-7410a38fc427 with generation 2 is now empty (__consumer_offsets-33) (kafka.coordinator.group.GroupCoordinator)
[2018-08-20 17:22:41,426] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:22:41,427] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:22:42,648] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:22:42,649] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:22:44,445] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:22:44,447] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:22:46,172] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:22:46,173] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:22:47,453] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:22:47,454] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:22:49,156] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:22:49,157] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:22:50,888] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:22:50,889] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:22:52,372] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:22:52,373] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:22:53,841] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:22:53,842] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:22:54,969] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:22:54,970] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:22:57,066] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:22:57,067] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:22:58,799] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:22:58,800] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:23:00,193] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:23:00,194] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:23:01,996] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:23:01,997] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:23:03,248] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:23:03,249] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:23:04,898] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:23:04,899] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:23:06,784] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:23:06,785] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:23:08,838] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:23:08,839] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:23:10,079] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:23:10,080] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:23:11,758] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:23:11,759] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:23:13,698] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:23:13,699] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:23:15,688] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:23:15,689] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:23:17,609] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:23:17,610] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:23:19,395] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:23:19,396] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:23:20,505] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:23:20,506] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:23:22,226] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:23:22,227] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:23:23,481] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:23:23,482] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:23:25,209] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:23:25,210] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:23:26,761] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:23:26,762] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:23:28,575] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:23:28,577] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:23:30,335] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:23:30,336] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:23:32,256] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:23:32,257] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:23:34,218] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:23:34,219] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:23:36,020] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:23:36,021] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:23:38,101] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:23:38,102] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:23:39,831] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:23:39,832] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:23:41,441] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:23:41,442] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:23:43,346] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:23:43,347] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:23:45,109] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:23:45,110] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:23:46,771] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:23:46,772] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:23:48,039] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:23:48,040] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:23:49,646] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:23:49,647] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-20 17:23:50,883] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-20 17:23:50,884] WARN Session 0x1655553af610011 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
